# Generated by Django 5.1.4 on 2024-12-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
